version: "3"
services: 
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        volumes:
            - "./db_data:/var/opt/mssql/data"
        ports:
            - "1433:1433"
        user: root
        environment:
            SA_PASSWORD: "yourStrong(!)Password"
            ACCEPT_EULA: "Y"
    api:
        build: 
            context: ./backend/PDSACW
            dockerfile: Dockerfile
        ports: 
            - "5000:80"
    client:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        ports: 
            - "3000:3000"
    